DATAFRAME_DECIMALS:             8
FPS:                            50
SCENE_XMIN:                     -16.0
SCENE_XMAX:                     16.0
SCENE_YMIN:                     -9.0
SCENE_YMAX:                     9.0
SCREEN_WIDTH:                   1920
SCREEN_HEIGHT:                  1080
WINDOW_NAME:                    "The N-Body Problem"
TEXT_START_FRAC:                0.02
BAR_WIDTH_FRAC:                 0.02
BAR_SEP_FRAC:                   0.03
TEXT_OFFSET:                    0.02
INDICATORS_COLOR:               "gray75"
BACKGROUND_COLOR:               "gray10"
FONT:                           "Roboto-Bold"
FONT_SIZE:                      30
DEBUG_TEXT_SEP:                 14
FRAME_SKIP:                     1
GRID_COLOR:                     "gray25"
GRID_SEPARATION_PX:             90
GRID_MINOR_LW_PX:               1
GRID_MAJOR_LW_FACTOR:           3
ANIMATION_STARTUP_RUN_STATE:    0
ANIMATION_STARTUP_DEBUG_STATE:  1
COLOR_DEPTH:                    32
TIME_BAR_HEIGHT:                5